version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1010:1010"
    volumes:
      - .:/app

  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - URL=http://localhost:1010/swagger
